name: Print Git Environment Variables

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  print_git_env_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Git Environment Variables
        run: |
          env | grep ^GIT

      - name: Print Git Environment Variables
        run: |
          bash test.sh   

        
        