name: Print Branch Name

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  print_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Branch Name
        run: echo "The workflow is running on branch $GITHUB_REF"

        
        