name: Replace SSH Username

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  replace_ssh_username:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and replace SSH Username
        run: |
          ls
          pwd
        #   ssh_username=$(grep 'ssh_username' inputs.yaml | awk -F ': ' '{print $2}')
        #   sed -i "s/sshUserName: .*/sshUserName: $ssh_username/" new.yaml
        #   cat new.yaml  # Echo the replaced YAML content
